-- Generated by scripts/generate-journal.mjs. No real traveler data.
CREATE TRIGGER trace_cases_insert AFTER INSERT ON cases
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'cases',NEW.id,NEW.id,'INSERT',reason,NULL,json_set(NEW.data,'$.reference',NEW.reference),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_cases_update AFTER UPDATE ON cases WHEN json_set(OLD.data,'$.reference',OLD.reference) IS NOT json_set(NEW.data,'$.reference',NEW.reference)
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'cases',NEW.id,NEW.id,'UPDATE',reason,json_set(OLD.data,'$.reference',OLD.reference),json_set(NEW.data,'$.reference',NEW.reference),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_cases_delete AFTER DELETE ON cases
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'cases',OLD.id,OLD.id,'DELETE',reason,json_set(OLD.data,'$.reference',OLD.reference),NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_documents_insert AFTER INSERT ON documents
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'documents',NEW.id,NEW.case_id,'INSERT',reason,NULL,json_set(NEW.data,'$.fileSha256',NEW.sha256),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_documents_update AFTER UPDATE ON documents WHEN json_set(OLD.data,'$.fileSha256',OLD.sha256) IS NOT json_set(NEW.data,'$.fileSha256',NEW.sha256)
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'documents',NEW.id,NEW.case_id,'UPDATE',reason,json_set(OLD.data,'$.fileSha256',OLD.sha256),json_set(NEW.data,'$.fileSha256',NEW.sha256),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_documents_delete AFTER DELETE ON documents
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'documents',OLD.id,OLD.case_id,'DELETE',reason,json_set(OLD.data,'$.fileSha256',OLD.sha256),NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_case_details_insert AFTER INSERT ON case_details
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'case_details',NEW.case_id,NEW.case_id,'INSERT',reason,NULL,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_case_details_update AFTER UPDATE ON case_details WHEN OLD.data IS NOT NEW.data
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'case_details',NEW.case_id,NEW.case_id,'UPDATE',reason,OLD.data,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_case_details_delete AFTER DELETE ON case_details
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'case_details',OLD.case_id,OLD.case_id,'DELETE',reason,OLD.data,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_intake_requests_insert AFTER INSERT ON intake_requests
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'intake_requests',NEW.id,NULL,'INSERT',reason,NULL,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_intake_requests_update AFTER UPDATE ON intake_requests WHEN OLD.data IS NOT NEW.data
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'intake_requests',NEW.id,NULL,'UPDATE',reason,OLD.data,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_intake_requests_delete AFTER DELETE ON intake_requests
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'intake_requests',OLD.id,NULL,'DELETE',reason,OLD.data,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_directive_records_insert AFTER INSERT ON directive_records
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'directive_records',NEW.id,NEW.case_id,'INSERT',reason,NULL,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_directive_records_update AFTER UPDATE ON directive_records WHEN OLD.data IS NOT NEW.data
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'directive_records',NEW.id,NEW.case_id,'UPDATE',reason,OLD.data,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_directive_records_delete AFTER DELETE ON directive_records
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'directive_records',OLD.id,OLD.case_id,'DELETE',reason,OLD.data,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_workflow_cases_insert AFTER INSERT ON workflow_cases
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'workflow_cases',NEW.case_id,NEW.case_id,'INSERT',reason,NULL,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_workflow_cases_update AFTER UPDATE ON workflow_cases WHEN OLD.data IS NOT NEW.data
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'workflow_cases',NEW.case_id,NEW.case_id,'UPDATE',reason,OLD.data,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_workflow_cases_delete AFTER DELETE ON workflow_cases
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'workflow_cases',OLD.case_id,OLD.case_id,'DELETE',reason,OLD.data,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_operational_decisions_insert AFTER INSERT ON operational_decisions
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'operational_decisions',NEW.id,NULL,'INSERT',reason,NULL,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_operational_decisions_update AFTER UPDATE ON operational_decisions WHEN OLD.data IS NOT NEW.data
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'operational_decisions',NEW.id,NULL,'UPDATE',reason,OLD.data,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_operational_decisions_delete AFTER DELETE ON operational_decisions
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'operational_decisions',OLD.id,NULL,'DELETE',reason,OLD.data,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_workspace_settings_insert AFTER INSERT ON workspace_settings
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'workspace_settings',NEW.owner,NULL,'INSERT',reason,NULL,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_workspace_settings_update AFTER UPDATE ON workspace_settings WHEN OLD.data IS NOT NEW.data
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'workspace_settings',NEW.owner,NULL,'UPDATE',reason,OLD.data,NEW.data,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_workspace_settings_delete AFTER DELETE ON workspace_settings
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'workspace_settings',OLD.owner,NULL,'DELETE',reason,OLD.data,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_staff_users_insert AFTER INSERT ON staff_users
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'staff_users',NEW.id,NULL,'INSERT',reason,NULL,json_object('username',NEW.username,'displayName',NEW.display_name,'role',NEW.role,'active',NEW.active,'revision',NEW.revision),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_staff_users_update AFTER UPDATE ON staff_users WHEN json_object('username',OLD.username,'displayName',OLD.display_name,'role',OLD.role,'active',OLD.active,'revision',OLD.revision) IS NOT json_object('username',NEW.username,'displayName',NEW.display_name,'role',NEW.role,'active',NEW.active,'revision',NEW.revision)
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'staff_users',NEW.id,NULL,'UPDATE',reason,json_object('username',OLD.username,'displayName',OLD.display_name,'role',OLD.role,'active',OLD.active,'revision',OLD.revision),json_object('username',NEW.username,'displayName',NEW.display_name,'role',NEW.role,'active',NEW.active,'revision',NEW.revision),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_staff_users_delete AFTER DELETE ON staff_users
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'staff_users',OLD.id,NULL,'DELETE',reason,json_object('username',OLD.username,'displayName',OLD.display_name,'role',OLD.role,'active',OLD.active,'revision',OLD.revision),NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER trace_packet_reviews_insert AFTER INSERT ON packet_reviews
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'packet_reviews',NEW.id,NEW.case_id,'INSERT',reason,NULL,NEW.snapshot,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_packet_reviews_update AFTER UPDATE ON packet_reviews WHEN OLD.snapshot IS NOT NEW.snapshot
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=NEW.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT NEW.owner,token,actor,actor_name,'packet_reviews',NEW.id,NEW.case_id,'UPDATE',reason,OLD.snapshot,NEW.snapshot,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=NEW.owner;
END;
CREATE TRIGGER trace_packet_reviews_delete AFTER DELETE ON packet_reviews
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=OLD.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT OLD.owner,token,actor,actor_name,'packet_reviews',OLD.id,OLD.case_id,'DELETE',reason,OLD.snapshot,NULL,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=OLD.owner;
END;
CREATE TRIGGER bump_case_data AFTER UPDATE OF data ON cases WHEN OLD.data IS NOT NEW.data BEGIN UPDATE cases SET revision=revision+1 WHERE id=NEW.id; END;
CREATE TRIGGER bump_documents_insert AFTER INSERT ON documents BEGIN UPDATE cases SET revision=revision+1 WHERE id=NEW.case_id; END;
CREATE TRIGGER bump_documents_update AFTER UPDATE ON documents BEGIN UPDATE cases SET revision=revision+1 WHERE id=NEW.case_id; END;
CREATE TRIGGER bump_documents_delete AFTER DELETE ON documents BEGIN UPDATE cases SET revision=revision+1 WHERE id=OLD.case_id; END;
CREATE TRIGGER bump_case_details_insert AFTER INSERT ON case_details BEGIN UPDATE cases SET revision=revision+1 WHERE id=NEW.case_id; END;
CREATE TRIGGER bump_case_details_update AFTER UPDATE ON case_details BEGIN UPDATE cases SET revision=revision+1 WHERE id=NEW.case_id; END;
CREATE TRIGGER bump_case_details_delete AFTER DELETE ON case_details BEGIN UPDATE cases SET revision=revision+1 WHERE id=OLD.case_id; END;
