"use client";
import { useState } from "react";
import { Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { CaseRecord } from "@/lib/sanad/types";
import { recordAnalytics, analyticsCsv, followupLabels, type FollowupStatus } from "@/lib/sanad/operations";
import { normalizeDetails, validRecordedDate, type RecordedDate } from "@/lib/sanad/traveler";
import { DateField, RecordedValue } from "./traveler-panel";

export default function Analytics({ records, onOpenCase }: { records: CaseRecord[]; onOpenCase: (id: string) => void }) {
  const [asOf, setAsOf] = useState<RecordedDate>({ value: new Date().toISOString().slice(0, 10), calendar: "gregorian" }), [visa, setVisa] = useState("all"), [status, setStatus] = useState<FollowupStatus | "all">("all");
  const valid = !!asOf.value && validRecordedDate(asOf.value, asOf.calendar), stats = recordAnalytics(records, valid ? asOf : { ...asOf, value: "" }, visa), rows = stats.rows.filter(r => status === "all" || r.status === status);
  function download() { const url = URL.createObjectURL(new Blob([analyticsCsv(records, asOf, visa)], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `SANAD-records-${asOf.value}.csv`; link.click(); URL.revokeObjectURL(url); }
  return <><div className="page-heading"><div><div className="eyebrow">أرقام من السجلات المتاحة</div><h1>الإحصاءات والمتابعة</h1><p>تغطية الملفات وحركات السفر ومواعيد المغادرة المسجلة.</p></div><Button variant="outline" onClick={download} disabled={!valid}><Download size={17}/>تصدير CSV</Button></div><div className="simulation-banner"><strong>نطاق الإحصائية: ملفات سَنَد التجريبية فقط</strong><span>ليست إحصاءً لجميع الوافدين في المملكة. غياب خروج مرتبط لا يثبت بقاء الشخص أو مخالفته. لا تُستخدم هذه اللوحة لتنفيذ إجراء.</span></div>
  <section className="ops-card analytics-filters"><DateField label="تاريخ رصد السجلات" value={asOf} onChange={setAsOf}/><div className="field"><label htmlFor="analytics-visa">نوع التأشيرة</label><select id="analytics-visa" className="ops-select" value={visa} onChange={e => setVisa(e.target.value)}><option value="all">جميع التأشيرات</option>{[...new Set(records.map(r => r.visaType))].map(v => <option key={v}>{v}</option>)}</select></div><div className="field"><label htmlFor="analytics-status">تصفية المتابعة</label><select id="analytics-status" className="ops-select" value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="all">كل السجلات</option>{Object.entries(followupLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></section>{!valid && <p className="form-error" role="alert">أدخل تاريخ رصد صالحًا وفق التقويم المختار.</p>}
  <div className="ops-metrics">{[["ملفات ضمن التصفية", stats.total], ["حركات دخول مسجلة", stats.entryRecords], ["حركات لها خروج مسجل", stats.exitRecords], ["حركات دون خروج مرتبط", stats.missingExitRecords]].map(([label, value]) => <section className="ops-card" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><p className="traveler-footnote">عدادات الحركات تشمل كل الحركات المحفوظة ضمن تصفية التأشيرة. تاريخ الرصد يخص تصنيف المتابعة أدناه. الملف ليس بالضرورة شخصًا فريدًا على مستوى المملكة.</p>
  <div className="analytics-columns"><section className="ops-card"><h2>الملفات حسب نوع التأشيرة</h2>{stats.visaCounts.map(v => <div className="visa-count-row" key={v.type}><span>{v.type}</span><div><i style={{ width: `${100 * v.count / Math.max(1, stats.total)}%` }}/></div><strong>{v.count}</strong></div>)}{!stats.total && <p>لا توجد ملفات ضمن التصفية.</p>}</section><section className="ops-card"><h2>متابعة الحركة المحددة كآخر دخول</h2>{Object.entries(followupLabels).map(([k, label]) => <button className="followup-count" key={k} onClick={() => setStatus(k as FollowupStatus)}><span>{label}</span><strong>{stats.counts[k as FollowupStatus]}</strong></button>)}</section></div>
  <section className="ops-card"><h2>سجلات تحتاج تحقق الموظف</h2><p className="traveler-footnote">الموعد يُدخل من «معلومات المسافر ← تعديل الخانات ← موعد المغادرة حسب المصدر». لا يُستنتج من انتهاء التأشيرة. التواريخ ذات التقويم المختلف تبقى «بيانات غير كافية».</p><div className="table-scroll"><table className="ops-table"><thead><tr><th>الملف</th><th>التأشيرة</th><th>موعد المغادرة المدخل</th><th>نتيجة مقارنة السجل</th><th>فتح</th></tr></thead><tbody>{rows.map(({ record, status }) => { const due = normalizeDetails(record.details).profile.dates.departureDeadline; return <tr key={record.id}><td><strong>{record.name}</strong><small><bdi>{record.reference}</bdi></small></td><td>{record.visaType}</td><td>{due.value ? <><RecordedValue value={due.value}/> {due.calendar === "hijri" ? "هجري" : "ميلادي"}</> : "غير مدخل"}</td><td>{followupLabels[status]}</td><td><Button size="sm" variant="outline" aria-label={`فتح سجل ${record.reference}`} onClick={() => onOpenCase(record.id)}><FileText size={15}/>الملف</Button></td></tr>; })}</tbody></table>{!rows.length && <p className="movement-empty">لا توجد سجلات بهذه التصفية.</p>}</div></section></>;
}
