"use client";
import { useEffect, useRef, useState } from "react";
import { Sparkles, ArrowUp, ExternalLink, Loader2, Cpu, CheckCircle2, AlertCircle, MessageSquareText, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Answer, CaseRecord, Evidence, fieldLabels } from "@/lib/sanad/types";
import type { Intent } from "@/lib/sanad/domain";
import type { AiConfiguration } from "@/lib/sanad/ai-config";
import { api } from "./workspace";
export default function Assistant({record,onEvidence}:{record:CaseRecord;onEvidence:(e:Evidence)=>void}){
  const [query,setQuery]=useState("");const [busy,setBusy]=useState(false);const [answer,setAnswer]=useState<Answer|null>(null);const [question,setQuestion]=useState("");const [error,setError]=useState("");const [modelStatus,setModelStatus]=useState<"off"|"loading"|"ready"|"error">("off");const [modelProgress,setModelProgress]=useState("");
  const [config,setConfig]=useState<AiConfiguration|null>(null);const [configError,setConfigError]=useState(false);const groqReady=!!config?.generativeConfigured;const [provider,setProvider]=useState<"groq"|"local">("local");
  useEffect(()=>{let mounted=true;const refresh=()=>api<AiConfiguration>("/api/ai-config").then(next=>{if(mounted){setConfig(next);setConfigError(false);setProvider(current=>next.generativeConfigured?current:"local");}}).catch(()=>{if(mounted)setConfigError(true);});api<AiConfiguration>("/api/ai-config").then(next=>{if(mounted){setConfig(next);setProvider(next.generativeConfigured?"groq":"local");}}).catch(()=>{if(mounted)setConfigError(true);});window.addEventListener("focus",refresh);return()=>{mounted=false;window.removeEventListener("focus",refresh);};},[]);
  const worker=useRef<Worker|null>(null);const pending=useRef(new Map<string,{resolve:(v:{intent:Intent|null;score:number})=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>());const active=useRef(record.id);
  useEffect(()=>{active.current=record.id;},[record.id]);
  const recordVersion=record.id+record.updatedAt;const [answerVersion,setAnswerVersion]=useState(recordVersion);
  if(answerVersion!==recordVersion){setAnswerVersion(recordVersion);setAnswer(null);setQuestion("");setError("");}
  useEffect(()=>()=>{worker.current?.terminate();pending.current.forEach(p=>{clearTimeout(p.timer);p.reject(Error("المساعد أغلق"));});pending.current.clear();},[]);
  function call(type:"load"|"query",text?:string){
    if(!worker.current){worker.current=new Worker("/ai/semantic-worker.js",{type:"module"});worker.current.onmessage=event=>{
      const m=event.data;if(m.type==="progress"){if(m.detail?.status==="progress")setModelProgress(`تحميل النموذج ${Math.round(m.detail.progress||0)}٪`);return;}const p=pending.current.get(m.id);if(!p)return;clearTimeout(p.timer);pending.current.delete(m.id);if(m.type==="error")p.reject(Error("تعذر تشغيل النموذج المحلي. الاستعلام المباشر ما زال متاحًا."));else p.resolve(m);
    };worker.current.onerror=()=>{pending.current.forEach(p=>{clearTimeout(p.timer);p.reject(Error("تعذر تشغيل النموذج على هذا المتصفح."));});pending.current.clear();worker.current?.terminate();worker.current=null;setModelStatus("error");};}
    return new Promise<{intent:Intent|null;score:number}>((resolve,reject)=>{const id=crypto.randomUUID();const timer=setTimeout(()=>{pending.current.delete(id);reject(Error("استغرق النموذج وقتًا طويلًا. جرّب مجددًا أو استخدم الأسئلة المباشرة."));},type==="load"?600_000:60_000);pending.current.set(id,{resolve,reject,timer});worker.current!.postMessage({id,type,query:text});});
  }
  async function enable(){setModelStatus("loading");setModelProgress("تحميل النموذج المفتوح أول مرة…");try{await call("load");setModelStatus("ready");setModelProgress("");}catch(e){setModelStatus("error");setModelProgress((e as Error).message);worker.current?.terminate();worker.current=null;}}
  async function ask(text:string){if(text.trim().length<2||busy)return;const id=record.id;setBusy(true);setError("");setQuestion(text);setQuery("");try{let intent:Intent|null|undefined;let semantic=false;if(provider==="local"&&modelStatus==="ready"){const found=await call("query",text);intent=found.intent;semantic=true;}const response=await api<Answer>("/api/assistant",{method:"POST",body:JSON.stringify({caseId:id,query:text,intent,semantic,provider})});if(active.current===id)setAnswer(response);}catch(e){if(active.current===id)setError((e as Error).message);}finally{setBusy(false);}}
  return <aside className="assistant-panel"><div className="assistant-heading"><span className="assistant-emblem"><Sparkles size={22}/></span><div><h2>مساعد سَنَد</h2><span>إجابة واضحة. مصدر ظاهر.</span></div><span className="ai-label">AI</span></div>{(configError||config?.status!=="enabled")&&<p className="model-explainer" role="status">{configError?"تعذر تحديث إعداد المساعد؛ أعد فتح الملف للمحاولة.":!config?"جارٍ فحص إعداد Groq…":config.status==="disabled"?"مفتاح Groq محفوظ. التفعيل متوقف من إعدادات مسؤول النظام.":"Groq غير مهيأ: يلزم إضافة المفتاح إلى أسرار الخادم ثم تفعيله من إعدادات الحماية."}</p>}{groqReady&&<div className="groq-selector"><Select value={provider} onValueChange={v=>setProvider(v as "groq"|"local")} disabled={busy}><SelectTrigger aria-label="مزود مساعد سند"><SelectValue/></SelectTrigger><SelectContent dir="rtl"><SelectItem value="groq">Groq · صياغة مسودة بالمصادر</SelectItem><SelectItem value="local">المساعد المحلي · على جهازك</SelectItem></SelectContent></Select><small>{provider==="groq"?"تُرسل نصوص السؤال والمراجع الاصطناعية إلى Groq. لا تُرسل صور الوثائق. أسئلة التأشيرة والحركات تُجاب من السجل مباشرة.":"معالجة محلية للسؤال، ثم قراءة من سجلات سَنَد."}</small></div>}{provider==="local"&&<div className="model-bar"><Cpu size={16}/><div><strong>{modelStatus==="ready"?"الفهم الدلالي المحلي مفعّل":modelStatus==="loading"?"تجهيز النموذج المحلي":"الاستعلام المباشر متاح"}</strong><small>{modelStatus==="ready"?"نموذج متعدد اللغات · بدون مفتاح API":modelStatus==="loading"?modelProgress:"فعّل النموذج لفهم صيغ أسئلة متنوعة"}</small></div>{modelStatus!=="ready"&&<Button size="sm" variant="outline" aria-label="تفعيل النموذج المحلي" disabled={modelStatus==="loading"} onClick={enable}>{modelStatus==="loading"?<Loader2 className="spin"/>:modelStatus==="error"?<RotateCcw size={15}/>:"تفعيل"}</Button>}</div>}{provider==="local"&&modelStatus==="off"&&<p className="model-explainer">يُحمّل النموذج المفتوح أول مرة من Hugging Face. معالجة السؤال تتم على جهازك.</p>}{provider==="local"&&modelStatus==="error"&&<p className="model-error" role="status">{modelProgress}</p>}
    <div className="assistant-body">{!question&&!answer?<><div className="assistant-welcome"><MessageSquareText size={31}/><h3>كيف أساعدك في هذا الملف؟</h3><p>أسأل عن المستندات المحفوظة وبياناتها. كل مرجع يفتح موضعه في الملف.</p></div><div className="suggested-questions">{["اعرض صورة الجواز المتاحة","ما الاختلاف بين الوثيقة والسجل؟","هل الوثيقة البديلة محفوظة؟","جهّز ملخص الملف للمراجعة","اعرض بيانات التأشيرة","اعرض آخر دخول وخروج"].map(q=><button key={q} onClick={()=>ask(q)} disabled={busy}>{q}<ArrowUp size={15}/></button>)}</div></>:<><div className="user-question">{question}</div>{busy?<div className="assistant-thinking" role="status"><Loader2 className="spin"/><span>أراجع المستندات المتاحة…</span></div>:answer&&<div className="assistant-answer"><span className="answer-origin"><Sparkles size={15}/>{answer.mode==="generative"?"Groq · مسودة مولدة بالمراجع":answer.mode==="semantic"?"فهم دلالي محلي · إجابة من السجل":"استعلام مباشر من السجل"}</span><h3>{answer.title}</h3><p>{answer.text}</p>{answer.warning&&<p className="model-error" role="status">{answer.warning}</p>}{answer.verifiedText&&<details className="verified-answer"><summary>عرض نص السجل قبل الصياغة</summary><p>{answer.verifiedText}</p></details>}{answer.evidence.length>0&&<div className="evidence-list"><span>المراجع المتاحة</span>{answer.evidence.map(e=><button key={e.id} onClick={()=>onEvidence(e)}><span className="evidence-index">{answer.evidence.indexOf(e)+1}</span><span><strong>{e.field?fieldLabels[e.field]:e.label}</strong><small dir="auto">{e.value}</small></span><ExternalLink size={14}/></button>)}</div>}</div>}{error&&<div className="form-error" role="alert">{error}<Button variant="ghost" onClick={()=>ask(question)}>إعادة المحاولة</Button></div>}<button className="clear-chat" onClick={()=>{setAnswer(null);setQuestion("");setError("");}} disabled={busy}>بدء سؤال جديد</button></>}</div>
    <form className="assistant-input" onSubmit={e=>{e.preventDefault();void ask(query);}}><Textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسأل عن هذا الملف…" maxLength={700} aria-label="سؤالك لمساعد سند" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask(query);}}}/><Button size="icon" type="submit" disabled={busy||query.trim().length<2} aria-label="إرسال السؤال"><ArrowUp size={19}/></Button></form><p className="assistant-footnote"><ShieldCheckSmall/>ينقل ما في الملف. اعتماد المستند لدى الجهة المختصة.</p></aside>;
}
function ShieldCheckSmall(){return <CheckCircle2 size={13}/>;}
