"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Upload, Download, FileCheck2, FileWarning, CheckCircle2, Loader2, ExternalLink, ZoomIn, ZoomOut, ScanLine, FileText, Clock3, Link2, ShieldCheck, History, AlertTriangle, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import { AuditEvent, CaseRecord, Evidence, FieldKey, TravelFields, fieldLabels, consularLabels, emptyFields } from "@/lib/sanad/types";
import { discrepancies } from "@/lib/sanad/domain";
import { api, formatDate, StatusBadge } from "./workspace";
import Assistant from "./assistant";
import PacketHistory from "./packet-history";

export default function CaseDetail({record,audit,onBack,onUpload,onRefresh}:{record:CaseRecord;audit:AuditEvent[];onBack:()=>void;onUpload:()=>void;onRefresh:()=>Promise<void>}){
  const [docId,setDocId]=useState(record.documents.find(d=>d.type==="passport")?.id||record.documents[0]?.id||"");const [tab,setTab]=useState("documents");const [fields,setFields]=useState<TravelFields>(emptyFields());const [reviewNote,setReviewNote]=useState("");const [focus,setFocus]=useState<FieldKey|null>(null);const [zoom,setZoom]=useState(1);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [packet,setPacket]=useState(false);const [notes,setNotes]=useState(record.notes);const [consular,setConsular]=useState(record.consularStatus);const [packetDone,setPacketDone]=useState(false);
  const doc=record.documents.find(d=>d.id===docId)||record.documents.find(d=>d.type==="passport")||record.documents[0];
  useEffect(()=>{setDocId(record.documents.find(d=>d.type==="passport")?.id||record.documents[0]?.id||"");setTab("documents");setFocus(null);setZoom(1);setError("");setPacketDone(false);},[record.id]);
  useEffect(()=>{setFields(doc?.fields||emptyFields());setReviewNote(doc?.reviewNote||"");setError("");},[doc?.id,doc?.revision]);
  useEffect(()=>{setNotes(record.notes);setConsular(record.consularStatus);},[record.id,record.notes,record.consularStatus]);
  const differences=doc?discrepancies(record,{...doc,fields}):[];
  function evidence(e:Evidence){if(e.documentId){setDocId(e.documentId);setTab("documents");setFocus(e.field||null);}else setTab("record");}
  async function review(status:"approved"|"needs_correction"|"pending") {if(!doc)return;setBusy(true);setError("");try{await api(`/api/documents/${doc.id}`,{method:"PATCH",body:JSON.stringify({fields,reviewStatus:status,reviewNote,revision:doc.revision})});await onRefresh();toast.success(status==="approved"?"سُجلت مراجعة المستند":"حُفظت ملاحظات المراجعة");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function saveCase(){setBusy(true);setError("");try{await api(`/api/cases/${record.id}`,{method:"PATCH",body:JSON.stringify({notes,consularStatus:consular})});await onRefresh();toast.success("حُفظت متابعة الحالة");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function reviewPacket(){setBusy(true);try{await api(`/api/packet/${record.id}`,{method:"POST",body:"{}"});setPacketDone(true);await onRefresh();toast.success("سُجلت مراجعة الحزمة وحُفظت لقطة من بياناتها");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  const location=focus?doc?.locations[focus]:null;
  return <><button className="back-link" onClick={onBack}><ArrowRight size={17}/>كل الحالات</button><div className="case-detail-heading"><div className="case-person"><span className="large-avatar">{record.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><div className="case-title-line"><h1>{record.name}</h1><StatusBadge status={record.status}/></div><p><span dir="ltr">{record.reference}</span><span>•</span>{record.visaType}<span>•</span>دخول {formatDate(record.entryDate)}</p></div></div><div className="heading-actions"><Button variant="outline" onClick={onUpload}><Upload size={17}/>إرفاق وثيقة</Button><Button onClick={()=>{setPacket(true);setPacketDone(false);}}><FileCheck2 size={17}/>حزمة المراجعة</Button></div></div>
  <div className="case-context-bar"><span><Link2 size={16}/>رقم الحدود <strong dir="ltr">{record.borderNumber}</strong></span><span><FileText size={16}/>الجواز المسجل <strong dir="ltr">{record.passportNumber}</strong></span><span><Clock3 size={16}/>{consularLabels[record.consularStatus]}</span></div>
  <div className="case-workspace"><section className="review-workspace"><Tabs value={tab} onValueChange={setTab} dir="rtl"><div className="detail-tabs"><TabsList variant="line"><TabsTrigger value="documents"><FileText size={16}/>الوثائق والمراجعة</TabsTrigger><TabsTrigger value="record">سجل الحالة</TabsTrigger><TabsTrigger value="history">سجل الإجراءات</TabsTrigger></TabsList></div><TabsContent value="documents"><div className="documents-tab">
  {record.documents.length>0&&<div className="document-picker">{record.documents.map(d=><button key={d.id} onClick={()=>{setDocId(d.id);setFocus(null);setZoom(1);}} className={d.id===doc?.id?"active":""}><FileText size={16}/>{d.type==="passport"?"جواز السفر":"وثيقة بديلة"}<span className={`mini-review ${d.reviewStatus}`}/></button>)}</div>}
  {!doc?<div className="missing-document"><span><FileWarning size={38}/></span><h2>صورة الجواز غير مرفقة</h2><p>بيانات الدخول موجودة. أرفق نسخة متاحة من مصدر معلوم لبدء المراجعة.</p><Button onClick={onUpload}><Upload size={17}/>إرفاق النسخة المتاحة</Button><small>لا يمكن استرجاع مستند لم يُحفظ أصلًا.</small></div>:<><div className="document-toolbar"><span><FileText size={17}/>{doc.filename}</span><div><button className="icon-button" aria-label="تصغير المستند" disabled={zoom<=0.75} onClick={()=>setZoom(Math.max(0.75,zoom-0.25))}><ZoomOut size={17}/></button><span>{Math.round(zoom*100)}٪</span><button className="icon-button" aria-label="تكبير المستند" disabled={zoom>=2} onClick={()=>setZoom(Math.min(2,zoom+0.25))}><ZoomIn size={17}/></button><a href={`/api/documents/${doc.id}/file`} target="_blank" rel="noreferrer" className="icon-button" aria-label="فتح المستند الأصلي"><ExternalLink size={16}/></a></div></div><div className="document-viewer">{doc.contentType.startsWith("image/")?<div className="document-image-wrap" style={{width:`${zoom*100}%`}}><img src={`/api/documents/${doc.id}/file`} alt="المستند الاصطناعي المحفوظ للمراجعة"/>{location&&<span className="field-highlight" style={{left:`${location.x*100}%`,top:`${location.y*100}%`,width:`${location.width*100}%`,height:`${location.height*100}%`}}/>}</div>:<div className="pdf-placeholder"><FileText size={45}/><h3>مستند PDF محفوظ</h3><a href={`/api/documents/${doc.id}/file`} target="_blank" rel="noreferrer" className="text-link">فتح المستند للمراجعة<ExternalLink size={15}/></a></div>}</div>{focus&&<div className="focus-caption"><ScanLine size={15}/>{fieldLabels[focus]}: <strong dir="auto">{doc.fields[focus]||"غير مدخل"}</strong>{!location&&<span>راجع القيمة بصريًا؛ موضع النص غير متاح.</span>}<button onClick={()=>setFocus(null)} aria-label="إزالة تحديد الحقل"><X size={14}/></button></div>}<div className="document-source"><span><ShieldCheck size={15}/>{doc.source}</span><span>تقديم المستند: {formatDate(doc.capturedAt)}</span><span>{doc.extractionMethod==="tesseract"?"قراءة آلية محلية":doc.extractionMethod==="synthetic"?"حقول اصطناعية للتجربة":"إدخال يدوي"}</span></div>
  <div className="field-review"><div className="field-review-heading"><div><h2>مراجعة البيانات</h2><p>اضغط على الحقل لمراجعة مرجعه في الصورة.</p></div><span className={`review-pill ${doc.reviewStatus}`}>{doc.reviewStatus==="approved"?"سُجلت المراجعة":doc.reviewStatus==="needs_correction"?"طُلب تصحيح":"بانتظار المراجع"}</span></div>{differences.length>0&&<div className="difference-banner"><AlertTriangle size={18}/><span>{differences.length} اختلافات في الحقول. راجعها وسجّل ملاحظتك قبل الاعتماد.</span></div>}<div className="field-comparison"><div className="comparison-head"><span>الحقل</span><span>حسب الوثيقة — قابل للمراجعة</span><span>سجل الدخول</span></div>{(Object.keys(fieldLabels) as FieldKey[]).map(key=>{const original=({name:record.englishName,passportNumber:record.passportNumber,nationality:record.nationality,birthDate:record.birthDate,expiryDate:"—"})[key];return <div className={`comparison-row ${differences.includes(key)?"different":""} ${focus===key?"focused":""}`} key={key}><button className="field-name" onClick={()=>setFocus(key)}>{fieldLabels[key]}<ScanLine size={14}/></button><Input aria-label={`مراجعة ${fieldLabels[key]}`} dir="ltr" type={key.endsWith("Date")?"date":"text"} value={fields[key]} onFocus={()=>setFocus(key)} onChange={e=>setFields({...fields,[key]:e.target.value})} maxLength={160}/><span dir="ltr">{original}</span></div>;})}</div><div className="field"><Label htmlFor="review-note">ملاحظة المراجع {differences.length>0&&<span className="required-note">— مطلوبة لتوضيح الاختلاف</span>}</Label><Textarea id="review-note" value={reviewNote} onChange={e=>setReviewNote(e.target.value)} maxLength={2000} placeholder="اكتب ما راجعته، وسبب الاختلاف إن وجد…"/></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="review-actions"><Button onClick={()=>review("approved")} disabled={busy}>{busy?<Loader2 className="spin"/>:<CheckCircle2 size={17}/>}اعتماد مراجعة البيانات</Button><Button variant="outline" onClick={()=>review("needs_correction")} disabled={busy}>طلب تصحيح</Button><Button variant="ghost" onClick={()=>review("pending")} disabled={busy}>حفظ كمسودة</Button></div><p className="review-disclaimer">اعتماد المراجعة يسجل فحص الموظف للبيانات، ولا يصادق على أصالة الوثيقة أو جنسية حاملها.</p></div></>}
  </div></TabsContent><TabsContent value="record"><div className="record-tab"><h2>بيانات سجل الدخول</h2><div className="record-grid">{[["الاسم بالعربية",record.name],["الاسم بالإنجليزية",record.englishName],["رقم الحدود",record.borderNumber],["رقم التأشيرة",record.visaNumber],["الجنسية المسجلة",record.nationality],["تاريخ الميلاد",record.birthDate],["تاريخ الدخول",record.entryDate],["منفذ الدخول",record.port]].map(([label,value])=><div key={label}><span>{label}</span><strong dir="auto">{value}</strong></div>)}</div><div className="field"><Label>متابعة المراجعة القنصلية — إدخال الموظف</Label><Select value={consular} onValueChange={v=>setConsular(v as CaseRecord["consularStatus"])}><SelectTrigger aria-label="متابعة المراجعة القنصلية"><SelectValue/></SelectTrigger><SelectContent dir="rtl">{Object.entries(consularLabels).map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><div className="field"><Label htmlFor="case-notes">ملاحظات الحالة</Label><Textarea id="case-notes" value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)}/></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button onClick={saveCase} disabled={busy}>{busy&&<Loader2 className="spin"/>}حفظ المتابعة</Button></div></TabsContent><TabsContent value="history"><div className="case-history">{audit.map(a=><div className="history-item" key={a.id}><span><History size={16}/></span><div><strong>{a.detail}</strong><small>{formatDate(a.createdAt)} · {new Date(a.createdAt).toLocaleTimeString("ar-SA",{hour:"2-digit",minute:"2-digit"})}</small></div></div>)}{!audit.length&&<p>لا توجد إجراءات مسجلة للحالة.</p>}</div></TabsContent></Tabs></section><Assistant record={record} onEvidence={evidence}/></div>
  <Dialog open={packet} onOpenChange={setPacket}><DialogContent className="sanad-dialog packet-dialog" dir="rtl"><DialogHeader><span className="dialog-icon"><FileCheck2/></span><DialogTitle>حزمة المراجعة</DialogTitle><DialogDescription>{record.reference} — مستندات وبيانات من الملف الحالي، جاهزة للمراجعة والطباعة.</DialogDescription></DialogHeader><div className="packet-items">{record.documents.map(d=><div key={d.id}><FileText size={19}/><span>{d.type==="passport"?"جواز السفر":"الوثيقة البديلة"}<small>{d.source}</small></span><span className={`review-pill ${d.reviewStatus}`}>{d.reviewStatus==="approved"?"تمت المراجعة":"لم تعتمد"}</span></div>)}{!record.documents.length&&<p className="form-error">لا توجد وثائق مرفقة. ستحتوي المسودة بيانات السجل فقط.</p>}</div><p className="form-note">افتح المسودة وراجع محتواها. حفظ PDF متاح من نافذة الطباعة.</p><div className="packet-actions"><Button asChild><a href={`/api/packet/${record.id}`} target="_blank" rel="noreferrer"><Download size={17}/>فتح المسودة / حفظ PDF</a></Button><Button variant="outline" disabled={busy||packetDone||!record.documents.length||record.documents.some(d=>d.reviewStatus!=="approved")} onClick={reviewPacket}>{packetDone?<CheckCircle2/>:busy?<Loader2 className="spin"/>:<FileCheck2/>}{packetDone?"سُجلت المراجعة":"تسجيل مراجعة الحزمة"}</Button></div>{packet&&<PacketHistory key={String(packetDone)} caseId={record.id}/>}</DialogContent></Dialog>
  </>;
}
