"use client";
import { useEffect, useRef, useState } from "react";
import { UploadCloud, ScanLine, Loader2, FileText, CheckCircle2, AlertTriangle, Plus, X, Download } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { CaseRecord, TravelFields, FieldKey, emptyFields, fieldLabels } from "@/lib/sanad/types";
import { readImage, OcrResult } from "@/lib/sanad/ocr";
import { api } from "./workspace";

export function CreateCaseDialog({open,onOpenChange,onCreated}:{open:boolean;onOpenChange:(v:boolean)=>void;onCreated:(r:CaseRecord)=>Promise<void>}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [visa,setVisa]=useState("زيارة");const formRef=useRef<HTMLFormElement>(null);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);const values=Object.fromEntries(data);setBusy(true);try{const record=await api<CaseRecord>("/api/cases",{method:"POST",body:JSON.stringify({...values,visaType:visa,synthetic:true})});await onCreated(record);onOpenChange(false);formRef.current?.reset();toast.success("تم إنشاء الحالة");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog open={open} onOpenChange={v=>{if(!busy){onOpenChange(v);setError("");}}}><DialogContent className="sanad-dialog case-dialog" dir="rtl"><DialogHeader><span className="dialog-icon"><Plus/></span><DialogTitle>حالة تجريبية جديدة</DialogTitle><DialogDescription>أدخل بيانات وهمية لسجل الدخول. ستُرفق الوثائق داخل الملف.</DialogDescription></DialogHeader><form ref={formRef} onSubmit={submit}><div className="form-grid">{[{name:"name",label:"الاسم بالعربية",placeholder:"اسم تجريبي"},{name:"englishName",label:"الاسم في سجل الدخول بالإنجليزية",placeholder:"SAMPLE PERSON"},{name:"borderNumber",label:"رقم الحدود التجريبي",placeholder:"DEMO-B-1007"},{name:"visaNumber",label:"رقم التأشيرة التجريبي",placeholder:"DEMO-V-2007"},{name:"passportNumber",label:"رقم الجواز في السجل",placeholder:"SND000107"},{name:"nationality",label:"الجنسية المسجلة — بيانات تجريبية",placeholder:"UTO"},{name:"birthDate",label:"تاريخ الميلاد",type:"date"},{name:"entryDate",label:"تاريخ الدخول",type:"date"},{name:"port",label:"منفذ الدخول",placeholder:"منفذ تجريبي"}].map(f=><div className="field" key={f.name}><Label htmlFor={`new-${f.name}`}>{f.label}</Label><Input id={`new-${f.name}`} name={f.name} type={f.type||"text"} placeholder={f.placeholder} required maxLength={160} dir={f.name==="name"||f.name==="port"?"rtl":"ltr"}/></div>)}<div className="field"><Label>نوع التأشيرة</Label><Select value={visa} onValueChange={setVisa}><SelectTrigger aria-label="نوع التأشيرة"><SelectValue/></SelectTrigger><SelectContent dir="rtl">{["زيارة","عمرة","حج","عمل","سياحة","أخرى"].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></div></div><div className="field"><Label htmlFor="new-notes">ملاحظات الحالة</Label><Textarea id="new-notes" name="notes" maxLength={2000} placeholder="سبب الحاجة إلى الوثيقة أو ملاحظة للمراجع…"/></div><p className="form-note"><ShieldLabel/>هذه المساحة مخصصة لبيانات اصطناعية فقط.</p>{error&&<p className="form-error" role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)} disabled={busy}>إلغاء</Button><Button type="submit" disabled={busy}>{busy?<Loader2 className="spin"/>:<Plus/>}إنشاء الحالة</Button></DialogFooter></form></DialogContent></Dialog>;
}
function ShieldLabel(){return <CheckCircle2 size={16}/>;}
export function UploadDialog({record,onClose,onSaved}:{record:CaseRecord|null;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [fields,setFields]=useState<TravelFields>(emptyFields());const [source,setSource]=useState("");const [capturedAt,setCapturedAt]=useState("");const [type,setType]=useState("passport");const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [reading,setReading]=useState(false);const [progress,setProgress]=useState("");const [ocr,setOcr]=useState<OcrResult|null>(null);const [error,setError]=useState("");const [dragging,setDragging]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const generation=useRef(0);
  useEffect(()=>{generation.current++;setFile(null);setFields(emptyFields());setSource("");setCapturedAt(record?.entryDate||"");setType("passport");setConfirmed(false);setError("");setOcr(null);setProgress("");},[record?.id]);
  useEffect(()=>{if(!file){setPreview("");return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  function choose(next:File|undefined){if(!next||reading||busy)return;if(!["image/png","image/jpeg","application/pdf"].includes(next.type)){setError("استخدم صورة PNG أو JPEG أو ملف PDF.");return;}if(next.size>5*1024*1024||next.size===0){setError("أقصى حجم 5 ميجابايت، ولا يقبل الملف الفارغ.");return;}generation.current++;setFile(next);setOcr(null);setFields(emptyFields());setError("");setProgress("");}
  async function recognize(){if(!file)return;const current=generation.current;setReading(true);setError("");try{const result=await readImage(file,message=>{if(current===generation.current)setProgress(message);});if(current===generation.current){setOcr(result);setFields(result.fields);setProgress("اكتملت القراءة — راجع الحقول قبل الحفظ");}}catch(e){setError((e as Error).message);setProgress("");}finally{setReading(false);}}
  async function sample(){try{const response=await fetch("/samples/passport-sample.png");if(!response.ok)throw Error("تعذر تحميل المستند التجريبي");choose(new File([await response.blob()],"passport-sample.png",{type:"image/png"}));setSource("قناة التأشيرة — محاكاة");}catch(e){setError((e as Error).message);}}
  async function submit(event:React.FormEvent){event.preventDefault();if(!file||!record)return;setBusy(true);setError("");const data=new FormData();data.set("file",file);data.set("caseId",record.id);data.set("type",type);data.set("source",source);data.set("capturedAt",capturedAt);data.set("synthetic",String(confirmed));data.set("fields",JSON.stringify(fields));data.set("extractionMethod",ocr?"tesseract":"manual");data.set("extractedText",ocr?.text||"");data.set("locations",JSON.stringify(ocr?.locations||{}));if(ocr)data.set("confidence",String(ocr.confidence));try{await api("/api/documents",{method:"POST",body:data});await onSaved();toast.success("حُفظ المستند. يمكنك الآن مراجعة البيانات واعتمادها.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Dialog open={!!record} onOpenChange={v=>{if(!v&&!busy&&!reading)onClose();}}><DialogContent className="sanad-dialog upload-dialog" dir="rtl"><DialogHeader><span className="dialog-icon"><ScanLine/></span><DialogTitle>حفظ وثيقة جديدة</DialogTitle><DialogDescription>{record?.name} · {record?.reference} — ارفع نسخة تجريبية وراجع الحقول المقروءة.</DialogDescription></DialogHeader><form onSubmit={submit}><div className="upload-layout"><section><input ref={inputRef} type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>choose(e.target.files?.[0])} className="sr-only" aria-label="اختيار ملف الوثيقة" disabled={reading||busy}/>{!file?<div className={`dropzone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);choose(e.dataTransfer.files[0]);}}><UploadCloud size={37}/><h3>اسحب الوثيقة إلى هنا</h3><p>PNG أو JPEG أو PDF · حتى 5 ميجابايت</p><Button type="button" variant="outline" onClick={()=>inputRef.current?.click()}>اختيار ملف</Button><button type="button" className="text-link sample-link" onClick={sample}>استخدام جواز اصطناعي للتجربة</button></div>:<><div className="upload-preview">{file.type.startsWith("image/")?<img src={preview} alt="معاينة المستند المختار"/>:<div className="pdf-placeholder"><FileText size={46}/><span>ملف PDF</span><small>الحفظ متاح؛ أدخل الحقول يدويًا.</small></div>}</div><div className="selected-file"><div><FileText size={17}/><span>{file.name}</span><small>{(file.size/1024).toFixed(0)} KB</small></div><button type="button" className="icon-button" aria-label="إزالة الملف المختار" disabled={reading||busy} onClick={()=>{setFile(null);setOcr(null);setFields(emptyFields());}}><X size={17}/></button></div><Button type="button" variant="outline" className="ocr-button" onClick={recognize} disabled={reading||busy||file.type==="application/pdf"}>{reading?<Loader2 className="spin"/>:<ScanLine/>}{reading?"تجري القراءة على جهازك…":"قراءة المستند بالذكاء الاصطناعي"}</Button>{progress&&<p className="ocr-progress" role="status">{progress}</p>}{ocr&&<p className="form-note">جودة القراءة التقريبية {Math.round(ocr.confidence)}٪ — ليست درجة لصحة الوثيقة.</p>}</>}
      <div className="privacy-note"><CheckCircle2 size={17}/><p>قراءة الصورة تتم محليًا في المتصفح. تُرفع النسخة لمساحتك عند الضغط على حفظ.</p></div></section><section className="upload-fields"><div className="form-grid"><div className="field"><Label>نوع المستند</Label><Select value={type} onValueChange={setType}><SelectTrigger aria-label="نوع المستند"><SelectValue/></SelectTrigger><SelectContent dir="rtl"><SelectItem value="passport">جواز سفر</SelectItem><SelectItem value="travel_document">وثيقة سفر بديلة</SelectItem></SelectContent></Select></div><div className="field"><Label htmlFor="doc-date">تاريخ تقديم المستند</Label><Input id="doc-date" type="date" required value={capturedAt} onChange={e=>setCapturedAt(e.target.value)}/></div></div><div className="field"><Label htmlFor="doc-source">مصدر النسخة</Label><Input id="doc-source" placeholder="مثال: قناة التأشيرة — محاكاة" required minLength={2} maxLength={160} value={source} onChange={e=>setSource(e.target.value)}/></div><div className="fields-section-title"><span>حقول الوثيقة</span><small>يمكن ترك غير المقروء فارغًا للمراجعة</small></div>{(Object.keys(fieldLabels) as FieldKey[]).map(key=><div className="field compact-field" key={key}><Label htmlFor={`upload-${key}`}>{fieldLabels[key]}</Label><Input id={`upload-${key}`} type={key.endsWith("Date")?"date":"text"} dir="ltr" value={fields[key]} maxLength={key==="passportNumber"?40:160} onChange={e=>setFields({...fields,[key]:e.target.value})}/></div>)}</section></div><label className="checkbox-line"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><span>أؤكد أن المستند والبيانات تجريبية ولا تخص شخصًا حقيقيًا.</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={busy||reading}>إلغاء</Button><Button type="submit" disabled={!file||!confirmed||busy||reading}>{busy?<Loader2 className="spin"/>:<CheckCircle2/>}حفظ وإحالة للمراجعة</Button></DialogFooter></form></DialogContent></Dialog>;
}
