"use client";
import { useEffect, useState } from "react";
import { FileCheck2, Plus, Pencil, Loader2, Link2, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import type { CaseRecord } from "@/lib/sanad/types";
import { directiveReadiness, directiveTypes, type DirectiveRecord } from "@/lib/sanad/operations";
import { emptyDate, displayRecordedDate } from "@/lib/sanad/traveler";
import { DateField, InfoGrid } from "./traveler-panel";
import { api } from "./workspace";

type Draft = Pick<DirectiveRecord, "reference" | "type" | "source" | "date" | "documentIds" | "notes" | "synthetic">;
const blank = (): Draft => ({ reference: "", type: "entry_ban", source: "", date: emptyDate(), documentIds: [], notes: "", synthetic: true });
export default function Directives({ record, onRefresh, onDocument }: { record: CaseRecord; onRefresh: () => Promise<void>; onDocument: (id: string) => void }) {
  const [items, setItems] = useState<DirectiveRecord[]>([]), [open, setOpen] = useState(false), [draft, setDraft] = useState<Draft>(blank), [edit, setEdit] = useState<DirectiveRecord | null>(null), [key, setKey] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function refresh() { try { setItems(await api<DirectiveRecord[]>(`/api/cases/${record.id}/directives`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { setError(""); void refresh(); }, [record.id]);
  function start(item?: DirectiveRecord) { setDraft(item ? { reference: item.reference, type: item.type, source: item.source, date: { ...item.date }, documentIds: [...item.documentIds], notes: item.notes, synthetic: true } : blank()); setEdit(item || null); setKey(crypto.randomUUID()); setError(""); setOpen(true); }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await api(edit ? `/api/directives/${edit.id}` : `/api/cases/${record.id}/directives`, { method: edit ? "PATCH" : "POST", body: JSON.stringify({ ...draft, ...(edit ? { revision: edit.revision } : { requestKey: key }) }) }); await refresh(); await onRefresh(); setOpen(false); toast.success("حُفظ مرجع الأمر التجريبي ومستنداته"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function prepare(item: DirectiveRecord) { setBusy(true); setError(""); try { await api(`/api/directives/${item.id}/prepare`, { method: "POST", body: JSON.stringify({ revision: item.revision }) }); await refresh(); await onRefresh(); toast.success("حُفظت لقطة ثابتة من المستندات المرتبطة"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="travel-history"><div className="traveler-toolbar"><div><h2>الأوامر الواردة ومستنداتها</h2><p>حفظ مرجع الأمر ونسخ الوثائق للمراجعة.</p></div><Button onClick={() => start()}><Plus size={16}/>إضافة مرجع تجريبي</Button></div><div className="simulation-banner"><strong>سجل مستندات تجريبي</strong><span>إدخال مرجع لا يصدر أمرًا ولا يفعّل منع دخول أو إبعادًا. لا يوجد اتصال بقوائم رسمية.</span></div>{!open && error && <p className="form-error" role="alert">{error}</p>}
    {!items.length && <div className="travel-empty"><FileCheck2 size={35}/><h3>احفظ مرجع الأمر مع وثائقه</h3><p>يرتبط بالجواز وبالوثيقة البديلة إن كانت موجودة، حتى تبقى النسخ متاحة بعد المغادرة.</p></div>}
    {items.map(item => { const readiness = directiveReadiness(record, item.documentIds), docs = item.snapshot?.documents || record.documents.filter(d => item.documentIds.includes(d.id)); return <section className="ops-card directive-card" key={item.id}><div className="traveler-toolbar"><div><h3>{directiveTypes[item.type]}</h3><bdi>{item.reference}</bdi></div><span className="ops-status">{item.preparedAt ? "لقطة مستندات محفوظة" : "مسودة للمراجعة"}</span></div><InfoGrid rows={[["المصدر المدخل", item.source], ["تاريخ المرجع", displayRecordedDate(item.date)]]}/><p>{item.notes}</p><div className="directive-docs">{docs.map(d => <button key={d.id} onClick={() => onDocument(d.id)}><Link2 size={16}/>{d.type === "passport" ? "نسخة الجواز" : "الوثيقة البديلة"}<bdi>{d.fields.passportNumber}</bdi><small>{d.reviewStatus === "approved" ? "راجعها الموظف" : "تحتاج مراجعة"}</small></button>)}</div>{!item.preparedAt && !readiness.ready && <p className="traveler-footnote">ناقص للتجهيز: {readiness.missing.join("، ")}.</p>}<div className="traveler-form-actions">{!item.preparedAt && <><Button variant="outline" onClick={() => start(item)}><Pencil size={15}/>تعديل المرجع والروابط</Button><Button disabled={busy || !readiness.ready} onClick={() => prepare(item)}><FileCheck2 size={16}/>تثبيت حزمة المستندات</Button></>}<Button asChild variant="outline"><a href={`/api/directives/${item.id}/print`} target="_blank" rel="noreferrer"><Printer size={16}/>طباعة المرجع</a></Button></div>{item.preparedAt && <p className="traveler-footnote">اللقطة تحتفظ بالبيانات وبصمات الملفات وقت التجهيز. أي تصحيح لاحق يسجل بمرجع جديد.</p>}</section>; })}
    <Dialog open={open} onOpenChange={v => { if (!busy) setOpen(v); }}><DialogContent className="sanad-dialog traveler-dialog" dir="rtl"><DialogHeader><DialogTitle>{edit ? "تعديل مرجع وارد تجريبي" : "إضافة مرجع وارد تجريبي"}</DialogTitle><DialogDescription>استخدم أرقامًا ومصادر وهمية. هذا النموذج يحفظ المستندات ولا ينفذ أي أمر.</DialogDescription></DialogHeader><form onSubmit={save}><div className="form-grid"><div className="field"><Label htmlFor="directive-reference">رقم مرجع الأمر التجريبي</Label><Input id="directive-reference" required maxLength={80} value={draft.reference} placeholder="DEMO-ORDER-01" onChange={e => setDraft({ ...draft, reference: e.target.value })}/></div><div className="field"><Label htmlFor="directive-type">نوع المرجع الوارد</Label><select id="directive-type" className="ops-select" value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value as Draft["type"] })}>{Object.entries(directiveTypes).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></div><div className="field"><Label htmlFor="directive-source">مصدر الأمر — تجريبي</Label><Input id="directive-source" required maxLength={160} value={draft.source} onChange={e => setDraft({ ...draft, source: e.target.value })}/></div><DateField label="تاريخ الأمر الوارد" value={draft.date} onChange={date => setDraft({ ...draft, date })}/></div><h3 className="ops-form-title">النسخ المرتبطة بالمرجع</h3>{record.documents.map(d => <label className="checkbox-line" key={d.id}><input type="checkbox" checked={draft.documentIds.includes(d.id)} onChange={e => setDraft({ ...draft, documentIds: e.target.checked ? [...draft.documentIds, d.id] : draft.documentIds.filter(id => id !== d.id) })}/>{d.type === "passport" ? "جواز السفر" : "وثيقة بديلة"} · <bdi>{d.fields.passportNumber || d.filename}</bdi></label>)}{!record.documents.length && <p className="traveler-footnote">لا توجد نسخ مرفقة. تستطيع حفظ المرجع كمسودة ثم إرفاق المستندات من ملف الحالة وتحديث الروابط.</p>}<div className="field ops-notes"><Label htmlFor="directive-notes">ملاحظات مرجع الأمر</Label><Textarea id="directive-notes" maxLength={2000} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })}/></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="traveler-form-actions"><Button disabled={busy}>{busy && <Loader2 className="spin"/>}حفظ المرجع التجريبي</Button><Button variant="outline" type="button" onClick={() => setOpen(false)} disabled={busy}>إلغاء</Button></div></form></DialogContent></Dialog>
  </div>;
}
