"use client";
import { useState } from "react";
import { FileStack, LockKeyhole, ArrowLeft, Loader2, Eye, EyeOff, ShieldCheck } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
export default function LoginForm(){
  const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [visible,setVisible]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function login(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error||"تعذر تسجيل الدخول.");setPassword("");window.location.assign("/");}catch(e){setError((e as Error).message);setBusy(false);}}
  return <main className="login-page"><section className="login-story"><div className="login-brand"><span className="brand-symbol"><FileStack size={32}/></span><span>سَنَد</span></div><div className="login-story-copy"><span className="login-eyebrow">مرجع الوثيقة. وضوح المراجعة.</span><h1>كل معلومة،<br/>لها سَنَد.</h1><p>مساحة واحدة لحفظ وثائق السفر، مراجعة بياناتها، وتجهيز الملف من مصادره.</p><div className="login-trust"><ShieldCheck size={21}/><span>مصادر واضحة · مراجعة بشرية · بيانات تجريبية</span></div></div><span className="login-version">سَنَد — مساحة مراجعة الوثائق</span></section><section className="login-form-area"><form onSubmit={login} className="login-form"><span className="login-lock"><LockKeyhole size={25}/></span><h2>أهلًا بعودتك</h2><p>سجّل الدخول إلى مساحة سَنَد.</p><div className="field"><Label htmlFor="username">اسم المستخدم</Label><Input id="username" autoComplete="username" dir="ltr" value={username} onChange={e=>setUsername(e.target.value)} maxLength={80} required disabled={busy}/></div><div className="field"><Label htmlFor="password">كلمة المرور</Label><div className="password-field"><Input id="password" type={visible?"text":"password"} autoComplete="current-password" dir="ltr" value={password} onChange={e=>setPassword(e.target.value)} maxLength={200} required disabled={busy}/><Button type="button" variant="ghost" size="icon" onClick={()=>setVisible(!visible)} aria-label={visible?"إخفاء كلمة المرور":"إظهار كلمة المرور"}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</Button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" className="login-submit" disabled={busy||!username.trim()||!password}>{busy?<Loader2 className="spin" size={18}/>:<>دخول مساحة العمل<ArrowLeft size={18}/></>}</Button><small>بيانات الدخول تحصل عليها من مسؤول المشروع.</small></form></section></main>;
}
