"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Download, FileText, Loader2, Plus, RefreshCw, Send, PlaneLanding } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import { emptyFields, fieldLabels, type CaseRecord, type FieldKey, type TravelFields } from "@/lib/sanad/types";
import { intakeStatuses, visaTypes, type IntakeRecord } from "@/lib/sanad/operations";
import { api } from "./workspace";
import { InfoGrid } from "./traveler-panel";

export default function PreArrival({ onOpenCase, onRefresh }: { onOpenCase: (id: string) => void; onRefresh: () => Promise<void> }) {
  const [items, setItems] = useState<IntakeRecord[]>([]), [selected, setSelected] = useState<string | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [creating, setCreating] = useState(false), [arriving, setArriving] = useState(false), [busy, setBusy] = useState(false), [fields, setFields] = useState<TravelFields>(emptyFields), [note, setNote] = useState("");
  const record = items.find(r => r.id === selected);
  async function refresh() { try { setItems(await api<IntakeRecord[]>("/api/intake")); setError(""); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { setFields(record?.fields || emptyFields()); setNote(record?.reviewNote || ""); }, [record?.id, record?.revision]);
  async function action(kind: "review" | "dispatch" | "receive") { if (!record) return; setBusy(true); setError(""); try { const updated = await api<IntakeRecord>(`/api/intake/${record.id}/${kind}`, { method: kind === "review" ? "PATCH" : "POST", body: JSON.stringify({ revision: record.revision, ...(kind === "review" ? { fields, reviewNote: note } : {}) }) }); setItems(v => v.map(r => r.id === updated.id ? updated : r)); await onRefresh(); toast.success(intakeStatuses[updated.status]); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><div className="page-heading"><div><div className="eyebrow">المستند محفوظ قبل وصول المسافر</div><h1>ما قبل الوصول</h1><p>محاكاة حفظ نسخة الجواز عند التأشيرة وتسليمها إلى سَنَد.</p></div><Button onClick={() => setCreating(true)}><Plus size={18}/>طلب تجريبي جديد</Button></div>
    <div className="simulation-banner"><strong>محاكاة داخل سَنَد</strong><span>جهة إصدار تجريبية · قناة تسليم محلية · منفذ تجريبي. لا اتصال بالخارجية أو الداخلية، ولا إصدار تأشيرات فعلية.</span></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    {record ? <><button className="back-link" onClick={() => setSelected(null)}><ArrowRight size={17}/>كل طلبات ما قبل الوصول</button><div className="ops-heading"><div><h2>{record.name}</h2><p><bdi>{record.reference}</bdi> · {intakeStatuses[record.status]}</p></div><Button variant="outline" onClick={refresh}><RefreshCw size={15}/>تحديث الطلب</Button></div><div className="handoff-steps">{Object.entries(intakeStatuses).map(([key, label], i) => <div className={i <= Object.keys(intakeStatuses).indexOf(record.status) ? "complete" : ""} key={key}><span>{i + 1}</span><strong>{label}</strong></div>)}</div>
      <div className="intake-review-layout"><section className="ops-card"><h2>النسخة المحفوظة قبل الوصول</h2>{record.file.contentType.startsWith("image/") ? <img className="intake-image" src={`/api/intake/${record.id}/file`} alt="نسخة جواز اصطناعية محفوظة قبل الوصول"/> : <div className="travel-empty"><FileText size={40}/><p>نسخة PDF محفوظة</p></div>}<a className="text-link" href={`/api/intake/${record.id}/file`} target="_blank" rel="noreferrer">فتح النسخة الأصلية <Download size={15}/></a><InfoGrid rows={[["جهة الإصدار — محاكاة", record.issuer], ["تاريخ حفظ النسخة — ميلادي", record.capturedAt], ["رقم التأشيرة", record.visaNumber], ["نوع التأشيرة", record.visaType]]}/><p className="hash-line">SHA-256: <bdi>{record.file.sha256}</bdi></p></section>
      <section className="ops-card"><h2>المراجعة والتسليم</h2>{(["saved", "reviewed"] as string[]).includes(record.status) ? <><div className="form-grid">{(Object.keys(fieldLabels) as FieldKey[]).map(k => <div className="field" key={k}><Label htmlFor={`intake-review-${k}`}>{fieldLabels[k]}</Label><Input id={`intake-review-${k}`} dir="ltr" type={k.endsWith("Date") ? "date" : "text"} value={fields[k]} maxLength={160} onChange={e => setFields({ ...fields, [k]: e.target.value })}/></div>)}</div><div className="field"><Label htmlFor="intake-review-note">ملاحظة المراجع</Label><Textarea id="intake-review-note" value={note} maxLength={2000} onChange={e => setNote(e.target.value)} placeholder="ما الذي راجعته في النسخة؟"/></div><Button disabled={busy} onClick={() => action("review")}>{busy ? <Loader2 className="spin"/> : <CheckCircle2 size={17}/>}تسجيل مراجعة النسخة</Button><p className="traveler-footnote">تسجيل المراجعة فحص يدوي داخل النموذج، وليس إثباتًا للجنسية أو موافقة على تأشيرة.</p></> : <InfoGrid rows={Object.entries(record.fields).map(([k, v]) => [fieldLabels[k as FieldKey], v])}/>}
      {record.status === "reviewed" && <div className="handoff-action"><p>النسخة مراجعة. التسليم ينشئ رسالة تجريبية واحدة محفوظة داخل سَنَد.</p><Button disabled={busy} onClick={() => action("dispatch")}><Send size={16}/>تسليم النسخة — محاكاة</Button></div>}
      {record.status === "queued" && <div className="handoff-action"><p>الرسالة بانتظار الاستلام في جهة الوصول التجريبية.</p><Button disabled={busy} onClick={() => action("receive")}><Download size={16}/>محاكاة استلام النسخة</Button></div>}
      {record.messageId && <div className="delivery-receipt"><strong>إيصال التسليم التجريبي</strong><code>{record.messageId}</code><p>{record.receivedAt ? "سُجل الاستلام داخل النموذج. النسخة تحتفظ ببصمتها الأصلية." : "بانتظار تسجيل الاستلام."}</p></div>}
      {record.status === "received" && <div className="handoff-action"><p>النسخة جاهزة قبل الوصول. عند تسجيل الدخول ستُربط بالحالة دون تصوير الجواز مرة ثانية.</p><Button onClick={() => setArriving(true)}><PlaneLanding size={17}/>تسجيل دخول تجريبي وربط النسخة</Button></div>}
      {record.caseId && <Button onClick={() => onOpenCase(record.caseId!)}><FileText size={17}/>فتح ملف الحالة المرتبط</Button>}</section></div>
    </> : <section className="ops-card"><div className="traveler-toolbar"><div><h2>طلبات النسخ المبكرة</h2><p>{items.length} طلبًا تجريبيًا · لا تُحتسب كحالات دخول حتى تسجيل وصولها</p></div><Button variant="outline" onClick={refresh}><RefreshCw size={15}/>تحديث الطلبات</Button></div>{loading ? <p>تحميل الطلبات…</p> : !items.length ? <div className="travel-empty"><FileText size={35}/><h3>ابدأ بالنسخة قبل الوصول</h3><p>أنشئ طلبًا واختر «تعبئة مثال وهمي» لتجربة المسار كاملًا.</p></div> : <div className="intake-list">{items.map(r => <button key={r.id} onClick={() => setSelected(r.id)}><span><strong>{r.name}</strong><small><bdi>{r.reference}</bdi> · {r.visaType}</small></span><span className="ops-status">{intakeStatuses[r.status]}</span></button>)}</div>}</section>}
    <IntakeDialog open={creating} onClose={() => setCreating(false)} onSaved={async r => { await refresh(); setSelected(r.id); setCreating(false); }}/>
    {record && <ArrivalDialog open={arriving} record={record} onClose={() => setArriving(false)} onSaved={async () => { await refresh(); await onRefresh(); setArriving(false); toast.success("حُفظ الدخول ورُبطت النسخة السابقة بالحالة"); }}/>}</>;
}

const intakeInputs = [["name", "الاسم بالعربية"], ["englishName", "الاسم بالإنجليزية"], ["visaNumber", "رقم التأشيرة التجريبي"], ["issuer", "جهة إصدار التأشيرة — تجريبية"], ["capturedAt", "تاريخ حفظ النسخة — ميلادي"]] as const;
function IntakeDialog({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: (r: IntakeRecord) => Promise<void> }) {
  const [draft, setDraft] = useState({ name: "", englishName: "", visaNumber: "", issuer: "", capturedAt: "" }), [visa, setVisa] = useState("زيارة"), [fields, setFields] = useState<TravelFields>(emptyFields), [file, setFile] = useState<File | null>(null), [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [key, setKey] = useState("");
  useEffect(() => { if (open) { setKey(crypto.randomUUID()); setError(""); setFile(null); setConfirmed(false); setDraft({ name: "", englishName: "", visaNumber: "", issuer: "", capturedAt: new Date().toISOString().slice(0, 10) }); setFields(emptyFields()); } }, [open]);
  async function sample() { setBusy(true); setError(""); try { const response = await fetch("/samples/passport-sample.png"); if (!response.ok) throw Error("تعذر تحميل العينة"); setFile(new File([await response.blob()], "passport-sample.png", { type: "image/png" })); setFields({ name: "OMAR SALEM", passportNumber: "SND000101", nationality: "UTO", birthDate: "1990-04-12", expiryDate: "2030-04-12" }); setDraft({ name: "عمر — مثال قبل الوصول", englishName: "OMAR SALEM", visaNumber: `DEMO-PRE-${crypto.randomUUID().slice(0, 8)}`, issuer: "سفارة افتراضية للعرض", capturedAt: new Date(Date.now() - 86400000).toISOString().slice(0, 10) }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!file || !confirmed) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("file", file); form.set("metadata", JSON.stringify({ ...draft, visaType: visa, fields, synthetic: true, requestKey: key })); await onSaved(await api<IntakeRecord>("/api/intake", { method: "POST", body: form })); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={v => { if (!v && !busy) onClose(); }}><DialogContent className="sanad-dialog traveler-dialog" dir="rtl"><DialogHeader><DialogTitle>حفظ جواز قبل الوصول — محاكاة</DialogTitle><DialogDescription>طلب تجريبي بملف محفوظ فعليًا. لا يصدر تأشيرة ولا يرسل بيانات لجهة حكومية.</DialogDescription></DialogHeader><form onSubmit={submit}><Button type="button" variant="outline" onClick={sample} disabled={busy}>تعبئة مثال وهمي مع صورة العينة</Button><div className="field ops-file"><Label htmlFor="intake-file">نسخة الجواز التجريبية</Label><Input id="intake-file" type="file" accept="image/png,image/jpeg,application/pdf" disabled={busy} onChange={e => { setFile(e.target.files?.[0] || null); setKey(crypto.randomUUID()); }}/>{file && <small>{file.name} · {(file.size / 1024).toFixed(0)} KB</small>}</div><div className="form-grid">{intakeInputs.map(([k, label]) => <div className="field" key={k}><Label htmlFor={`intake-${k}`}>{label}</Label><Input id={`intake-${k}`} value={draft[k]} type={k === "capturedAt" ? "date" : "text"} required maxLength={k === "visaNumber" ? 40 : 160} onChange={e => setDraft({ ...draft, [k]: e.target.value })}/></div>)}<div className="field"><Label htmlFor="intake-visaType">نوع التأشيرة</Label><select id="intake-visaType" className="ops-select" value={visa} onChange={e => setVisa(e.target.value)}>{visaTypes.map(v => <option key={v}>{v}</option>)}</select></div></div><h3 className="ops-form-title">الحقول حسب النسخة — للمراجعة</h3><div className="form-grid">{(Object.keys(fieldLabels) as FieldKey[]).map(k => <div className="field" key={k}><Label htmlFor={`intake-field-${k}`}>{fieldLabels[k]}</Label><Input id={`intake-field-${k}`} dir="ltr" value={fields[k]} type={k.endsWith("Date") ? "date" : "text"} maxLength={160} onChange={e => setFields({ ...fields, [k]: e.target.value })}/></div>)}</div><label className="checkbox-line"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>المستند والبيانات وهمية ولا تخص شخصًا حقيقيًا</label>{error && <p className="form-error" role="alert">{error}</p>}<div className="traveler-form-actions"><Button disabled={busy || !file || !confirmed}>{busy && <Loader2 className="spin"/>}حفظ النسخة قبل الوصول</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>إلغاء</Button></div></form></DialogContent></Dialog>;
}
const arrivalInputs = [["borderNumber", "رقم الحدود التجريبي"], ["entryDate", "تاريخ الدخول — ميلادي"], ["time", "وقت الدخول"], ["port", "منفذ الدخول"], ["transport", "وسيلة الدخول"], ["direction", "جهة الدخول"], ["carrier", "الناقلة / الرحلة"], ["operatorNumber", "رقم المشغّل التجريبي"], ["documentNumber", "رقم وثيقة الدخول في الحركة"], ["movementReference", "رقم سجل السفر"]] as const;
function ArrivalDialog({ open, record, onClose, onSaved }: { open: boolean; record: IntakeRecord; onClose: () => void; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState<Record<typeof arrivalInputs[number][0], string>>({ borderNumber: "", entryDate: "", time: "", port: "", transport: "", direction: "", carrier: "", operatorNumber: "", documentNumber: "", movementReference: "" }), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (open) { setError(""); setDraft({ borderNumber: `DEMO-B-${record.id.slice(0, 8)}`, entryDate: new Date().toISOString().slice(0, 10), time: "09:15", port: "منفذ تجريبي", transport: "جوًا", direction: "جهة قدوم افتراضية", carrier: "ناقل افتراضي DEMO-01", operatorNumber: "DEMO-OP-01", documentNumber: `DEMO-IN-${record.id.slice(0, 8)}`, movementReference: `DEMO-TR-${record.id.slice(0, 8)}` }); } }, [open, record.id]);
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await api<CaseRecord>(`/api/intake/${record.id}/arrival`, { method: "POST", body: JSON.stringify({ ...draft, revision: record.revision }) }); await onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={v => { if (!v && !busy) onClose(); }}><DialogContent className="sanad-dialog traveler-dialog" dir="rtl"><DialogHeader><DialogTitle>تسجيل دخول تجريبي</DialogTitle><DialogDescription>سيُنشأ ملف الحالة وتُربط به النسخة المحفوظة سابقًا، دون إعادة رفعها.</DialogDescription></DialogHeader><form onSubmit={save}><div className="form-grid">{arrivalInputs.map(([k, label]) => <div className="field" key={k}><Label htmlFor={`arrival-${k}`}>{label}</Label><Input id={`arrival-${k}`} value={draft[k]} type={k === "entryDate" ? "date" : k === "time" ? "time" : "text"} required maxLength={k.includes("Number") ? 40 : 80} onChange={e => setDraft({ ...draft, [k]: e.target.value })}/></div>)}</div>{error && <p className="form-error" role="alert">{error}</p>}<div className="traveler-form-actions"><Button disabled={busy}>{busy && <Loader2 className="spin"/>}حفظ الدخول وربط النسخة</Button><Button type="button" variant="outline" onClick={onClose} disabled={busy}>إلغاء</Button></div></form></DialogContent></Dialog>;
}
