"use client";
import { useEffect, useState } from "react";
import { Plus, Minus, Pencil, PlaneLanding, PlaneTakeoff, Link2, Loader2, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import type { CaseRecord } from "@/lib/sanad/types";
import { displayRecordedDate, emptyDetails, emptyLeg, legFields, type TravelLeg, type TravelMovement } from "@/lib/sanad/traveler";
import { DateField, InfoGrid, RecordedValue } from "./traveler-panel";
import { api } from "./workspace";

type Draft = Omit<TravelMovement, "id" | "createdAt" | "updatedAt">;
export default function TravelHistory({ record, onRefresh, focusId, onDocument }: { record: CaseRecord; onRefresh: () => Promise<void>; focusId?: string; onDocument: (id: string) => void }) {
  const details = record.details || emptyDetails();
  const [expanded, setExpanded] = useState<string[]>([]), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [editId, setEditId] = useState(""), [revision, setRevision] = useState(details.revision), [latest, setLatest] = useState(false);
  const blank = (): Draft => ({ reference: "", visaNumber: record.visaNumber, source: "", entry: emptyLeg(), exit: emptyLeg() });
  const [draft, setDraft] = useState<Draft>(blank);
  useEffect(() => { if (focusId) { setExpanded(v => v.includes(focusId) ? v : [...v, focusId]); requestAnimationFrame(() => document.getElementById(`movement-${focusId}`)?.scrollIntoView({ block: "nearest", behavior: "smooth" })); } }, [focusId]);
  function edit(m?: TravelMovement) { setDraft(m ? structuredClone({ reference: m.reference, visaNumber: m.visaNumber, source: m.source, entry: m.entry, exit: m.exit }) : blank()); setEditId(m?.id || ""); setRevision(details.revision); setLatest(m?.id === details.latestEntryId); setError(""); setOpen(true); }
  function leg(side: "entry" | "exit", patch: Partial<TravelLeg>) { setDraft(d => ({ ...d, [side]: { ...d[side], ...patch } })); }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await api(`/api/cases/${record.id}/travel${editId ? `/${editId}` : ""}`, { method: editId ? "PATCH" : "POST", body: JSON.stringify({ revision, movement: draft, setLatestEntry: latest }) }); await onRefresh(); setOpen(false); toast.success("حُفظت حركة السفر وربط الوثائق"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function viewLeg(m: TravelMovement, side: "entry" | "exit") { const value = m[side], doc = record.documents.find(d => d.id === value.documentId); return <section className="movement-leg"><h4>{side === "entry" ? <PlaneLanding size={18}/> : <PlaneTakeoff size={18}/>}تفاصيل {side === "entry" ? "الدخول" : "الخروج"}</h4>{value.date.value ? <><InfoGrid rows={[["التاريخ", displayRecordedDate(value.date)], ["الوقت", value.time], ...legFields.map(([k, label]) => [label, value[k]])]}/>{doc ? <button className="linked-document" onClick={() => onDocument(doc.id)}><Link2 size={16}/>فتح النسخة المرتبطة: {doc.type === "passport" ? "جواز السفر" : "وثيقة بديلة"}<span dir="auto">{doc.fields.passportNumber || doc.filename}</span></button> : <p className="traveler-footnote">لا توجد نسخة وثيقة مرتبطة بهذه الحركة.</p>}</> : <p className="movement-empty">لا توجد بيانات خروج مسجلة في هذه الحركة. لا يُستنتج منها بقاء الشخص.</p>}</section>; }
  return <div className="travel-history"><div className="traveler-toolbar"><div><h2>سجل الدخول والخروج</h2><p>{details.movements.length} حركات محفوظة · مرتبة حسب الإضافة</p></div><Button onClick={() => edit()}><Plus size={17}/>إضافة حركة</Button></div><p className="traveler-footnote">رقم سجل السفر والوثيقة والمشغّل معرّفات مستقلة. يحدد الموظف آخر دخول؛ لا تُقارن التواريخ بين تقويمين مختلفين.</p>
    {!details.movements.length ? <div className="travel-empty"><PlaneLanding size={36}/><h3>أضف تفاصيل الحركة من السجل</h3><p>احفظ بيانات الدخول والخروج واربط كل جهة بنسخة وثيقتها.</p><Button variant="outline" onClick={() => edit()}>إضافة أول حركة</Button></div> : <div className="movement-list">{details.movements.map(m => { const isOpen = expanded.includes(m.id); return <article className="movement-card" id={`movement-${m.id}`} key={m.id}><button className="movement-summary" aria-expanded={isOpen} aria-controls={`movement-body-${m.id}`} onClick={() => setExpanded(v => isOpen ? v.filter(id => id !== m.id) : [...v, m.id])}><span className="movement-mark"><PlaneLanding size={20}/></span><span className="movement-main"><strong>سجل السفر <bdi dir="ltr">{m.reference}</bdi></strong><small>دخول: <RecordedValue value={displayRecordedDate(m.entry.date)}/> · {m.entry.location || "المنفذ غير مدخل"}</small><small>خروج: {m.exit.date.value ? <RecordedValue value={displayRecordedDate(m.exit.date)}/> : "غير مسجل في هذه الحركة"}</small></span>{m.id === details.latestEntryId && <span className="latest-pill">آخر دخول</span>}<span className="expand-mark" aria-hidden="true">{isOpen ? <Minus size={18}/> : <Plus size={18}/>}</span></button>{isOpen && <div className="movement-body" id={`movement-body-${m.id}`}><div className="movement-meta"><span>رقم التأشيرة: <b dir="ltr">{m.visaNumber || "غير مدخل"}</b></span><Button size="sm" variant="outline" onClick={() => edit(m)}><Pencil size={14}/>تعديل الحركة</Button></div><div className="movement-legs">{viewLeg(m, "entry")}{viewLeg(m, "exit")}</div><p className="traveler-footnote">المصدر: {m.source}</p></div>}</article>; })}</div>}
    <Dialog open={open} onOpenChange={v => { if (!busy) setOpen(v); }}><DialogContent className="sanad-dialog traveler-dialog" dir="rtl"><DialogHeader><DialogTitle>{editId ? "تعديل حركة السفر" : "إضافة حركة سفر"}</DialogTitle><DialogDescription>بيانات وهمية فقط. سجل الأرقام كما تظهر في المصدر؛ رقم الحركة قد يختلف عن رقم الجواز.</DialogDescription></DialogHeader><form onSubmit={save}><div className="form-grid"><div className="field"><Label htmlFor="movement-reference">رقم سجل السفر</Label><Input id="movement-reference" dir="ltr" value={draft.reference} maxLength={80} minLength={2} required onChange={e => setDraft({ ...draft, reference: e.target.value })}/></div><div className="field"><Label htmlFor="movement-visa">رقم التأشيرة للحركة</Label><Input id="movement-visa" dir="ltr" value={draft.visaNumber} maxLength={40} onChange={e => setDraft({ ...draft, visaNumber: e.target.value })}/></div></div>
    {(["entry", "exit"] as const).map(side => { const title = side === "entry" ? "الدخول" : "الخروج"; return <section className="movement-form-section" key={side}><h3>{title}{side === "exit" && <small>اختياري إذا لم تتوفر بياناته</small>}</h3><div className="form-grid"><DateField label={`تاريخ ${title}`} value={draft[side].date} onChange={date => leg(side, { date })}/><div className="field"><Label htmlFor={`${side}-time`}>وقت {title}</Label><Input id={`${side}-time`} type="time" step="1" value={draft[side].time} onChange={e => leg(side, { time: e.target.value })}/></div>{legFields.map(([key, label]) => <div className="field" key={key}><Label htmlFor={`${side}-${key}`}>{label} — {title}</Label><Input id={`${side}-${key}`} value={draft[side][key]} maxLength={160} onChange={e => leg(side, { [key]: e.target.value })}/></div>)}</div><div className="field movement-document-select"><Label htmlFor={`${side}-document`}>نسخة وثيقة {title} المحفوظة</Label><select id={`${side}-document`} value={draft[side].documentId} onChange={e => leg(side, { documentId: e.target.value })}><option value="">بدون ربط نسخة</option>{record.documents.map(d => <option value={d.id} key={d.id}>{d.type === "passport" ? "جواز" : "وثيقة بديلة"} · {d.fields.passportNumber || d.filename}</option>)}</select><small>الربط يفتح النسخة للمراجعة ولا يغيّر رقم الوثيقة المسجل في الحركة.</small></div></section>; })}
    <div className="field"><Label htmlFor="movement-source">مصدر بيانات الحركة</Label><Input id="movement-source" value={draft.source} maxLength={160} minLength={2} required placeholder="سجل سفر اصطناعي للعرض" onChange={e => setDraft({ ...draft, source: e.target.value })}/></div><label className="checkbox-line"><input type="checkbox" checked={latest} disabled={!!editId && editId === details.latestEntryId} onChange={e => setLatest(e.target.checked)}/>تحديد هذه الحركة كآخر دخول في الملف</label><p className="traveler-footnote">للتغيير إلى دخول آخر، حدده من تعديل الحركة المطلوبة. التواريخ الهجرية تُحفظ كما أُدخلت دون تحويل.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="traveler-form-actions"><Button type="submit" disabled={busy}>{busy && <Loader2 className="spin" size={16}/>}حفظ حركة السفر</Button><Button type="button" variant="outline" disabled={busy} onClick={() => setOpen(false)}>إلغاء</Button></div></form></DialogContent></Dialog>
  </div>;
}
