import test from 'node:test';
import assert from 'node:assert/strict';
import { answerFromRecord,caseStatus,discrepancies,directIntent,escapeHtml } from '../lib/sanad/domain';
import { dateString,newCaseSchema,reviewSchema,detectedMime } from '../lib/sanad/validation';
import { parseOcrText } from '../lib/sanad/ocr';
import { demoRecord } from '../lib/sanad/demo';
import type {CaseRecord,StoredDocument} from '../lib/sanad/types';
const r={...demoRecord(0),id:'case-test',reference:'TEST-01',documents:[],status:'needs_document',createdAt:'2026-09-11',updatedAt:'2026-09-11'} as CaseRecord;
const d={id:'doc-test',caseId:r.id,type:'passport',fields:{name:r.englishName,passportNumber:r.passportNumber,nationality:'UTO',birthDate:r.birthDate,expiryDate:'2030-04-12'},source:'synthetic test',reviewStatus:'approved',synthetic:true} as StoredDocument;
test('Missing original cannot be reconstructed from entry fields',()=>{const a=answerFromRecord(r,'passport');assert.match(a.text,/لا يمكن استعادة/);assert.equal(a.evidence.some(x=>x.documentId),false);});
test('Replacement only is preserved without claiming original exists',()=>{const record={...r,documents:[{...d,type:'travel_document' as const}]};assert.equal(caseStatus(record.documents),'needs_document');assert.match(answerFromRecord(record,'replacement').title,/متاحة/);});
test('Pending replacement prevents all-documents-reviewed state',()=>assert.equal(caseStatus([d,{...d,id:'d2',type:'travel_document',reviewStatus:'pending'}]),'needs_review'));
test('Name discrepancy is detected without changing entry record',()=>{const doc={...d,fields:{...d.fields,name:'SOMEONE ELSE'}};assert.deepEqual(discrepancies(r,doc),['name']);assert.equal(r.englishName,'OMAR SALIM');});
test('Alternative document may have a different number without a false conflict',()=>assert.deepEqual(discrepancies(r,{...d,type:'travel_document',fields:{...d.fields,passportNumber:'ALTERNATIVE-001'}}),[]));
test('Every answer citation resolves to a saved document field',()=>{const a=answerFromRecord({...r,documents:[d]},'summary');for(const e of a.evidence){assert.equal(e.documentId,d.id);assert.equal(e.value,d.fields[e.field!]);}});
test('Unsupported query does not fabricate an answer',()=>{const i=directIntent('كم سعر الذهب؟');assert.equal(i,null);assert.deepEqual(answerFromRecord(r,i).evidence,[]);});
test('Nationality answer is explicitly only document transcription',()=>assert.match(answerFromRecord({...r,documents:[d]},'nationality').text,/لا تمثل قرارًا مستقلًا/));
test('Reject invalid dates and real-data flag',()=>{assert.equal(dateString.safeParse('2026-02-30').success,false);assert.equal(dateString.safeParse('2024-02-29').success,true);const {consularStatus,...input}=demoRecord(0);assert.equal(newCaseSchema.safeParse({...input,synthetic:false}).success,false);});
test('Cannot approve incomplete review',()=>assert.equal(reviewSchema.safeParse({fields:{...d.fields,passportNumber:''},reviewStatus:'approved',reviewNote:'',revision:1}).success,false));
test('MIME detected from bytes rejects scripts and fake extensions',()=>{assert.equal(detectedMime(new TextEncoder().encode('<svg><script>alert(1)</script></svg>')),null);assert.equal(detectedMime(Uint8Array.from([137,80,78,71,13,10,26,10])),'image/png');});
test('Escapes packet HTML fields',()=>assert.equal(escapeHtml('<script>"&'), '&lt;script&gt;&quot;&amp;'));
test('OCR parser reads labeled fields and leaves absent fields empty',()=>{assert.equal(parseOcrText('NAME: TEST PERSON\nPASSPORT NUMBER: SND000101\nNATIONALITY: UTO\nDATE OF BIRTH: 1990-04-12\nDATE OF EXPIRY: 2030-04-12').passportNumber,'SND000101');assert.equal(parseOcrText('unreadable image').name,'');});
