// Generate database triggers: before/after and actor are committed with each business mutation.
import {writeFileSync} from 'node:fs';
const entities=[
 ['cases','id','id',"json_set(ROW.data,'$.reference',ROW.reference)"],
 ['documents','id','case_id',"json_set(ROW.data,'$.fileSha256',ROW.sha256)"],
 ['case_details','case_id','case_id','ROW.data'],
 ['intake_requests','id','NULL','ROW.data'],
 ['directive_records','id','case_id','ROW.data'],
 ['workflow_cases','case_id','case_id','ROW.data'],
 ['operational_decisions','id','NULL','ROW.data'],
 ['workspace_settings','owner','NULL','ROW.data'],
 ['staff_users','id','NULL',"json_object('username',ROW.username,'displayName',ROW.display_name,'role',ROW.role,'active',ROW.active,'revision',ROW.revision)"],
 ['packet_reviews','id','case_id','ROW.snapshot'],
];
let sql='-- Generated by scripts/generate-journal.mjs. No real traveler data.\n';
for(const [table,id,caseId,data] of entities)for(const operation of ['INSERT','UPDATE','DELETE']){
 const row=operation==='DELETE'?'OLD':'NEW';
 const before=operation==='INSERT'?'NULL':data.replaceAll('ROW','OLD');
 const after=operation==='DELETE'?'NULL':data.replaceAll('ROW','NEW');
 const condition=operation==='UPDATE'?`WHEN ${before} IS NOT ${after}`:'';
 sql+=`CREATE TRIGGER trace_${table}_${operation.toLowerCase()} AFTER ${operation} ON ${table} ${condition}
BEGIN
 SELECT RAISE(ABORT,'Missing mutation context') WHERE NOT EXISTS(SELECT 1 FROM mutation_context WHERE owner=${row}.owner AND expires_at>CAST(strftime('%s','now') AS INTEGER)*1000);
 INSERT INTO change_journal(owner,request_id,actor,actor_name,entity,entity_id,case_id,operation,reason,before_data,after_data,created_at)
 SELECT ${row}.owner,token,actor,actor_name,'${table}',${row}.${id},${caseId==='NULL'?'NULL':`${row}.${caseId}`},'${operation}',reason,${before},${after},strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM mutation_context WHERE owner=${row}.owner;
END;\n`;
}
// These revision changes deliberately do not journal metadata-only updates.
sql+=`CREATE TRIGGER bump_case_data AFTER UPDATE OF data ON cases WHEN OLD.data IS NOT NEW.data BEGIN UPDATE cases SET revision=revision+1 WHERE id=NEW.id; END;\n`;
for(const table of ['documents','case_details'])for(const op of ['INSERT','UPDATE','DELETE']){
 const row=op==='DELETE'?'OLD':'NEW';
 sql+=`CREATE TRIGGER bump_${table}_${op.toLowerCase()} AFTER ${op} ON ${table} BEGIN UPDATE cases SET revision=revision+1 WHERE id=${row}.case_id; END;\n`;
}
writeFileSync('drizzle/0005_journal_triggers.sql',sql.replace(/[ \t]+$/gm,''));
console.log('Generated scoped, append-only change-journal triggers.');
